# Generated by Django 2.2.7 on 2019-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abiliity',
            name='avatar',
        ),
        migrations.AddField(
            model_name='abiliity',
            name='avatar',
            field=models.ManyToManyField(to='game.Avatar'),
        ),
        migrations.RemoveField(
            model_name='knowing',
            name='avatar',
        ),
        migrations.AddField(
            model_name='knowing',
            name='avatar',
            field=models.ManyToManyField(to='game.Avatar'),
        ),
    ]
