# Generated by Django 2.2.7 on 2019-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191118_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowing',
            name='force',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Abiliity',
        ),
    ]
