# Generated by Django 2.2.7 on 2019-11-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191119_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowing',
            name='avatar',
        ),
        migrations.AddField(
            model_name='avatar',
            name='knowing',
            field=models.ManyToManyField(to='game.Knowing'),
        ),
    ]
