# Generated by Django 2.2.7 on 2019-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20191119_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('force', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('allowed_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='avatar',
            name='item',
            field=models.ManyToManyField(to='game.Item'),
        ),
    ]
