# Generated by Django 2.2.7 on 2019-11-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20191119_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='defence',
            new_name='defense',
        ),
    ]
